### ISSUE TITLE
flask default_handler import error

### ISSUE THREAD

**Issue by ericmartens** [pmservice/cars-4-you#1]
In wml_utils.py, importing default_handler from Flask throws an error in Flask-0.11.1. Switching the Flask version in requirements.txt to Flask-1.0.2 fixes the error

**Comment by Maksymilian-Erazmus1** [comment]
Flask version has been updated in requirements.txt file.

https://github.com/pmservice/cars-4-you/commit/c24225f5a6d594a602b3611cbd531d41d173e533
